version: '3'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: maestru-app
    ports:
      - '${APP_PORT}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      WWWGROUP: '${WWWGROUP}'
    volumes:
      - '.:/var/www/maestru'
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db

  db:
    image: 'mysql:8.0'
    container_name: maestru-db
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - './docker/db:/var/lib/mysql'
